version: "3.7"

services:
  app:
    build: .
    ports:
      - 80:80
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432