version: "3.7"

services:
  app:
    build: .
    ports:
      - 8000:80
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432